mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # include is function it take all urls from polls app urls
                  path('', include('polls.urls')),
                  # path('', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('polls/', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/result/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('<int:pk>/adminview/', views.AdminView.as_view(), name='adminview'),
    path('table/', views.TableView.as_view(), name='table'),
    path('calender/', views.CalenderView.as_view(), name='calender'),
    path('', views.user_login, name='login'),
    path('<int:user_id>/edit/', views.edit, name='edit'),
    path('delete/', views.delete_user, name='delete'),
    path('ajaxaction/', views.ajax_request, name='ajaxaction'),
    path('square/', views.SquareForm.as_view(), name='square'),
    path('pdf/', views.pdf_file, name='pdf'),
    path('pdf/<int:pdf_id>', views.pdf_view, name='pdfview'),
    path('create_square_customer',views.square_customer_form,name='create_square_customer')
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_recently_published(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_recently_published.admin_order_field = 'pub_date'
    was_recently_published.boolean = True
    was_recently_published.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class UserProfileImg(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'


class UserRole(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    USER = 'user'
    ADMIN = 'admin'
    user_option = [
        (USER, 'USER'),
        (ADMIN, 'ADMIN')
    ]
    role = models.CharField(max_length=5, choices=user_option, default=USER, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Role'


class UploadPdf(models.Model):
    pdf_name = models.CharField(max_length=100, blank=True)
    pdf_file = models.FileField(upload_to='pdf', blank=True, null=True)
    zip_file = models.FileField(upload_to='zip_file', blank=True, null=True)

    def __str__(self):
        return self.pdf_name

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfileImg, UserRole, UploadPdf


class CreateUser(UserCreationForm):
    password2 = None
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}, render_value=True),
                                required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'required': False}),
            # 'email':forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control'}))
            # 'password1': forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

        }


class EditForm(forms.Form):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}),
                                 required=False)
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)


# login form
class LoginUser(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_password(self):
        password_passed = self.cleaned_data.get('password')
        username = self.cleaned_data.get('username')

        qs = User.objects.filter(username=username)
        if not qs[0].password in password_passed:
            return forms.ValidationError('incorrect Password ')


class ProfileImgForm(forms.ModelForm):
    class Meta:
        model = UserProfileImg
        fields = ['picture']


class UserRoleForm(forms.ModelForm):
    class Meta:
        model = UserRole
        fields = ['role']
        widgets = {
            'role': forms.Select(attrs={'class': 'form-control'})

        }


class PdfFileUpload(forms.ModelForm):
    class Meta:
        model = UploadPdf
        fields = ['pdf_name', 'pdf_file','zip_file']
        widgets = {
            'pdf_name': forms.TextInput(attrs={'class': 'form-control'})
        }


class SquareCustomer(forms.Form):
    customer_name = forms.CharField(max_length=254,widget=forms.TextInput(attrs={'class':'form-control'}))
    customer_email = forms.EmailField(max_length=254,widget=forms.EmailInput(attrs={'class':'form-control'}))

polls/views.py
import json
import PyPDF2, os
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from zipfile import ZipFile
from .forms import CreateUser, LoginUser, ProfileImgForm, UserRoleForm, EditForm, PdfFileUpload, SquareCustomer
from .models import Question, Choice, UploadPdf


class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/'
    template_name = 'polls/index.html'
    # for override automatic creating context name
    context_object_name = 'lastest_question'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class CalenderView(generic.TemplateView):
    template_name = 'polls/calender.html'


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class SquareForm(generic.TemplateView):
    template_name = 'square/sqform.html'


# class SquareCutomerForm(generic.TemplateView):
#     template_name = 'square/customer.html'
#     form_class = SquareCustomer


def square_customer_form(request):
    form = SquareCustomer
    context = {
        'form':form
    }
    return render(request,'square/customer.html',context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    print(question)
    print(request.POST)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {'question': question, 'error_msg': "You didn't selected the choice"}
        return render(request, 'polls/detail.html', context)
    else:
        selected_choice.vote += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=question.id))


def signup(request):
    if request.method == 'POST':
        form = CreateUser(request.POST)
        p_form = ProfileImgForm(request.POST, request.FILES)
        role_form = UserRoleForm(request.POST)
        if form.is_valid() and p_form.is_valid() and role_form.is_valid():
            user = form.save()
            user.save()
            role = role_form.save(commit=False)
            profile = p_form.save(commit=False)
            profile.user = user
            role.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                profile.save()
                print(profile.picture.url)
                role.save()
            else:
                print('Picture is not Saved')
    form = CreateUser()
    p_form = ProfileImgForm()
    role_form = UserRoleForm
    context = {'form': form, 'p_form': p_form, 'role_form': role_form}

    return render(request, 'polls/signup.html', context)


def user_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user_1 = User.objects.filter(username=username).first()
    user = authenticate(request, username=username, password=password)
    if user is not None:
        if user_1.userrole.role == 'admin':
            login(request, user)
            return redirect('polls:table')
        elif user_1.userrole.role == 'user':
            login(request, user)
            return redirect('polls:index')
    form = LoginUser()
    context = {'form': form}
    return render(request, 'polls/login.html', context)


# mixinins for adminview
class UserGetMixin:
    model = User

    def get_queryset(self):
        return User.objects.all()


class AdminView(UserGetMixin, LoginRequiredMixin, generic.DetailView):
    # model = User
    login_url = '/'
    template_name = 'polls/admin.html'

    # def get_queryset(self):
    #     return User.objects.all()


class TableView(generic.ListView):
    template_name = 'polls/table.html'
    context_object_name = 'all_user'

    # fetching all user from database except admin user
    def get_queryset(self):
        return [user for user in User.objects.all()]


# for logout user from the app
def user_logout(request):
    logout(request)
    return redirect('polls:login')


# for editing user from the app
def edit(request, user_id):
    edit_user = User.objects.get(id=user_id)
    # instance is used for displaying fields
    form = EditForm(initial={'password1': edit_user.password, 'username': edit_user.username,
                             'first_name': edit_user.first_name, 'last_name': edit_user.last_name})
    context = {
        'edit_user': edit_user,
        'form': form
    }
    return render(request, 'polls/signup.html', context)


# user deleting from the app
def delete_user(request, user_id):
    user_del = User.objects.get(id=user_id)
    print(user_del)
    if request.method == 'POST':
        user_del.delete()
        return redirect('polls:adminview', pk=user_id)
    context = {
        'user_del': user_del
    }
    return render(request, 'polls/delete.html', context)
    # return JsonResponse(user_del)


# class AjaxRequest(generic.View):
def ajax_request(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    form_value = request.POST.get('formData')
    data = dict()
    if request.is_ajax():
        if action == "DELETE":
            qs = User.objects.get(id=user_id)
            qs.delete()
            all_user = User.objects.all()
            data['html_view'] = render_to_string('polls/table.html', {'all_user': all_user})
            return JsonResponse(data)
        elif action == "EDIT":
            edit_user = User.objects.get(id=user_id)
            if request.method == "POST":
                form = EditForm(request.POST,
                                initial={'password1': edit_user.password, 'username': edit_user.username,
                                         'first_name': edit_user.first_name, 'last_name': edit_user.last_name})
                if form.is_valid():
                    json_for = json.loads(form_value)
                    first_name = json_for[1]['value']
                    last_name = json_for[2]['value']
                    username = json_for[3]['value']
                    edit_user.first_name = first_name
                    edit_user.last_name = last_name
                    edit_user.username = username
                    edit_user.save()
                    all_user = User.objects.all()
                    data['table_view'] = render_to_string('polls/table.html', {'all_user': all_user})
                    return HttpResponse(json.dumps(data), content_type="application/json")
        elif action == "payment":
            from square.client import Client
            import uuid
            client = Client(
                access_token='EAAAEKGHC9ln1ADjUHupUnQH3F5yd7OwCrLsc9DLRQxrs2OF1qgHNOTL_NYFycne',
                environment='sandbox',
            )

            data['action'] = request.POST.get('action')
            nonce = request.POST.get('nonce')
            idempotency_key = uuid.uuid4().hex[:16]
            body = {
                "source_id": nonce,
                "idempotency_key": idempotency_key,
                "amount_money": {
                    "amount": int('100'),
                    "currency": "USD"
                },
            }
            if nonce:
                payment_api = client.payments
                result = payment_api.create_payment(body)
                if result.is_success():
                    print(result.body)
            else:
                payment_api = client.payments
                result = payment_api.create_payment(body)
                # try:
                #     err_code = str(result.errors[0].get("category"))
                # except:
                #     err_code = ""
                data['status'] = False
                # data['message'] = "Payment Failed: ERROR CODE  {}".format(err_code)
                print(result.is_error)
            return HttpResponse(json.dumps(data), content_type="application/json")
        elif action == 'create_square_customer':
            from square.client import Client
            import uuid
            client = Client(
                access_token='EAAAEKGHC9ln1ADjUHupUnQH3F5yd7OwCrLsc9DLRQxrs2OF1qgHNOTL_NYFycne',
                environment='sandbox',
            )
            idempotency_key = uuid.uuid4().hex[:16]
            form_data = request.POST.get('formValues')
            json_form = json.loads(form_data)
            customer_name = json_form[1]['value']
            customer_email = json_form[2]['value']
            body = {
                "idempotency_key": idempotency_key,
                "given_name": customer_name,
                "email_address": customer_email
            }
            result = client.customers.create_customer(body)
            if result.is_success():
                print(result.body)
            elif result.is_error():
                print(result.errors)
            print(f"customer_name:{customer_name}, customer_email:{customer_email}")
            return HttpResponse(json.dumps(data),content_type="application/json")



def pdf_file(request):
    if request.method == 'POST':
        form = PdfFileUpload(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('polls:pdf')
    else:
        form = PdfFileUpload()

templates/polls/admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Admin Panel{% endblock %}

{% block content %}
   {% if request.user.userrole == 'user' %}
        <p>You Have no Permission to view this page</p>
    {% else %}
       {% if object %}
                <div class="container mt-4 user-info">
                <div class="media mt-1" id="userprofile">
                <div class="media-body">
                <h3 class="mt-0 mb-1 ml-5">User info</h3>
                <ul>
                    <li class="mt-1">First name:{{ object.first_name }}</li>
                    <li class="mt-1">Last name:{{ object.last_name }}</li>
                    <li class="mt-1">Username:{{ object.username }}</li>
                </ul>
                </div>
                <img src="{{ object.userprofileimg.picture.url }}" class=" ml-3 rounded" alt="{{ object.userprofileimg.picture.url }}" height="100" width="100">
                </div>
                    {% csrf_token %}
                    <a href="{% url 'polls:edit' object.id%}" class="btn-sm btn-primary ml-4 ">Edit</a>
                    <button type="button"  id="btn-delete" class="btn-sm btn-danger" >Delete</button>
                </div>
                <hr/>
            {% else %}
           <p>No users found</p>
           {% endif %}


        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                ...
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="modal-submit" data-id={{object.id}} data-name={{ object.username }}  data-url="{% url 'polls:ajaxaction'%}">Save changes</button>
              </div>
            </div>
          </div>
        </div>
   {% endif %}
{#    {% include 'polls/table.html' %}#}



{% endblock %}

templates/polls/calender.html
{% extends 'base.html' %}


{% block js %}
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'dayGridMonth'
        });
        calendar.render();
      });
{% endblock %}


{% block content %}
    <div class="container">
    <div id='calendar' class="mt-5"></div>
    </div>
{% endblock %}

templates/polls/delete.html
{% extends 'base.html' %}

{% block titile %} Delete {% endblock %}

{% block content %}
<div class="container">
<div class="jumbotron">
  {%  if user_del %}
    <h1 class="display-4">Do You Want to Delete "{{user_del.username}}"</h1>
      <p>{{ user_del.id }}</p>
        <form  method="POST" class="mt-2">
            {% csrf_token %}
            <a  href="{% url 'p:login' %}" class="btn btn-primary">Cancel</a>
            <button id="btn-del" type="button" class="btn btn-danger" data-id="{{ user_del.id }}" >Delete</button>
        </form>
    {% endif %}
</div>
</div>
{% endblock %}

templates/polls/detail.html
{% extends 'base.html' %}

{% block titile %}

    {{ question.question_text }}
{% endblock %}
{% block content %}
    <div class="container bg-light mx-auto mt-5 w-50">
        <div class="p-5">
            <h1>{{ question.question_text }}</h1>

         {% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

        <form action="{% url 'p:vote' question.id %}" method="POST">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <input class="btn btn-primary" type="submit" value="Vote">
        </form>
        </div>
    </div>
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}
{% load static %}
{% block titile %}Polls Page{% endblock %}
{% block content %}
    <p>{{ perms.createuser }}</p>
    {%   if perms %}
        <div class="container mt-5">
                            <div class="col-md-6 mx-auto bg-light rounded p-3">
                                {% if lastest_question %}
                                    <h3 class="h3 text-center m-2 ">Please Vote</h3>
                                    <ul>
                                        {% for question in lastest_question %}
                                            <li><a href="{% url 'p:detail' question.id %}"  class="badge badge-danger p-2 m-1" >{{ question.question_text }}</a></li>
                                        {% endfor %}
                                    </ul>
                            </div>
                                {% else %}
                                <p>No polls are available</p>
                                {% endif %}
        </div>
    {% endif %}
{% endblock %}

templates/polls/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="login">
{#        <h3 class="text-center text-white pt-5">Login form</h3>#}
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post">
                            {% csrf_token %}
                            <h3 class="text-center text-info">Login</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Username:</label><br>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Password:</label><br>
                                {{ form.password }}
                            </div>
                            <div class="form-group">
                                <label for="remember-me" class="text-info"> </label><br>
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                            </div>
                            <div id="register-link" class="text-right">
                                <a href="{% url 'polls:signup'%}" class="text-info">Register here</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>










{% endblock %}

templates/polls/pdf_view.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5 bg-info w-50 rounded">
        <form method="POST" enctype="multipart/form-data" class="p-5">
            <h2>PDF Upload</h2>
                {% csrf_token %}
                {{ form.as_p }}
            <button class="btn btn-primary btn-sm" type="submit">Upload</button>
        </form>
    </div>
    <div class="container mt-3 w-50">
        <table class="table">
            <thead>
                <tr>
                  <th scope="col">PDF Name</th>
                  <th scope="col">View PDF</th>
                </tr>
            </thead>
            <tbody>
            {% for pdf in qs %}
                <tr>
                <td>
                    {{ pdf.pdf_name }}
                </td>
                <td>
                    <a href="{% url 'polls:pdfview' pdf.id %}" class="btn btn-danger btn-sm">Check PDF</a>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/polls/pdftext.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        {% if pdf_html %}
            {% for pdf in pdf_html %}
                <p>{{ pdf }}</p>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/polls/result.html
{% extends 'base.html' %}

{% block titile %}
    Result
{% endblock %}
    {% block content %}
    <div class="container bg-light">
    <div class="p-5">
        <h2>Vote Result</h2>
        <hr/>
        <h2>{{ question.question_text }}</h2>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}</li>
            {% endfor %}
        </ul>
        <a class="btn btn-primary" href="{% url 'p:detail' question.id %}">Vote again?</a>
    </div>
    </div>
    {% endblock %}

templates/polls/signup.html
{% extends 'base.html' %}
{% load static %}

{% if request.user.is_authenticte %}
    {% block title %} Update{% endblock %}
{% else %}
{#    {% block title %} Sign up{% endblock %}#}
{% endif %}
{% block content %}
    <div class="container mt-3 bg-light shadow rounded w-50 ">
        <form method="POST"  id="signup-form" enctype="multipart/form-data" class="polls-4">
            {% csrf_token %}
  <!-- 2 column grid layout with text inputs for the first and last names -->
          <div class="row mb-4">
            <div class="col">
              <div class="form-outline">
                <label class="form-label" for="form3Example1">First name</label>
                  {{ form.first_name }}
              </div>
            </div>
            <div class="col">
              <div class="form-outline">
                  <label class="form-label" for="form3Example2">Last name</label>
                    {{ form.last_name }}
              </div>
            </div>
          </div>

          <!-- Username input -->
          <div class="form-outline mb-4">
            <label class="form-label" for="form3Example3">Username</label>
              {{ form.username }}
          </div>

          <!-- Check User or Admin -->
            {% if request.user.userrole.role == 'admin' %}
{#                <div class="form-outline mb-4">#}
{#                    <label for="exampleFormControlSelect1">Select Role</label>#}
{#                    {{ role_form.role }}#}
{#                </div>#}
            {% else %}
                <div class="form-outline mb-4">
                    <label class="form-label" for="form3Example4">Password</label>
                        {{ form.password1 }}
                </div>
                <div class="form-outline mb-4">
                    <label class="form-label" for="form3Example4">Profile Photo</label>
                    {{ p_form.picture }}
                </div>
                <div class="form-outline mb-4">
                    <label for="exampleFormControlSelect1">Select Role</label>
                    {{ role_form.role }}
                </div>
            {% endif %}

          <!-- Submit button -->
            {% if request.user.userrole.role == 'admin' %}
                <button id="update-btn" type="button" class="btn btn-danger btn-block " data-url="{% url 'polls:ajaxaction' %}" data-id={{ edit_user.id }} data-username={{ edit_user.username }} data-firstname={{ edit_user.first_name }} data-lastname={{ edit_user.last_name }} >Update</button>
                {% else %}
                <button type="submit" class="btn btn-primary btn-block mb-4">Sign up</button>
            {% endif %}
        </form>
    </div>
{% endblock %}

templates/polls/sucess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if user.is_superuser %}
    <h1>User is not Logged in</h1>
    <p>{{ request.user }}</p>
{% elif request.user.is_authenticated %}
    <p>{{ request.user.is_authenticated }}</p>
    <h1>Welcome you are Logged in </h1>
    <h2>You are logged in as {{ user }}</h2>
    <form method="POST"> 
        {% csrf_token %}
    <button type="submit">Log Out</button>
    </form>
{% endif %}
</body>
</html>

templates/polls/table.html
{#{% extends 'base.html' %}#}

{% block content %}
    <div class="container">
        {% if all_user %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">First</th>
              <th scope="col">Last</th>
              <th scope="col">Handle</th>
            </tr>
          </thead>
          <tbody>
            {% for object in all_user %}
                {% if object.userrole.role == 'user' %}
                    <tr>
                      <td>{{ object.first_name }}</td>
                      <td>{{ object.last_name }}</td>
                      <td>
                          <a href="{% url 'polls:adminview'  object.id %}">{{ object.username }}</a>
                      </td>
                    </tr>
                {% endif %}
            {% endfor %}
          </tbody>
    </table>
    {% else %}
            <h1>No User Found,Please Add User</h1>
    {% endif %}
    </div>
{% endblock %}