mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # include is function it take all urls from polls app urls
                  path('', include('polls.urls')),
                  # path('', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('polls/', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/result/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('<int:pk>/adminview/', views.AdminView.as_view(), name='adminview'),
    path('table/', views.TableView.as_view(), name='table'),
    path('calender/', views.CalenderView.as_view(), name='calender'),
    path('', views.user_login, name='login'),
    path('<int:user_id>/edit/', views.edit, name='edit'),
    path('delete/', views.delete_user, name='delete'),
    path('ajaxaction/', views.ajax_request, name='ajaxaction'),
    path('square/', views.SquareForm.as_view(), name='square'),
    path('pdf/', views.pdf_file, name='pdf'),
    path('pdf/<int:pdf_id>', views.pdf_view, name='pdfview'),
    path('create_square_customer',views.square_customer_form,name='create_square_customer')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/main.css'%}">
    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.3.2/main.min.css' rel='stylesheet' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.3.2/main.min.js'></script>

    <script>
    {% block js %}
    {% endblock %}
    </script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container polls-0">
      <a class="navbar-brand" href="#">POLL APP</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        {% if  request.user.is_authenticated %}
            {% if request.user.is_superuser %}
                <li class="nav-item mr-auto">
                <a class="nav-link" href="{% url 'polls:logout' %}">Logout</a>
                </li>
            {% else %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle navbar-brand" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{{  user.userprofileimg.picture.url}}" class="navbar-brand rounded-circle" width="40" height="40" alt="No img"/>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'polls:logout'%}">Logout</a>
            </div>
      </li>
                {% endif %}
        {% else %}
        <li class="nav-item mr-auto">
            <a class="nav-link" href="{% url 'polls:login' %}">Login</a>
        </li>
            <li class="nav-item mr-auto">
            <a class="nav-link" href="{% url 'polls:signup' %}">Signup</a>
            </li>

        {% endif %}
    </ul>
  </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/calender.js' %}"></script>
{% block javascript %} {% endblock %}
{#<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>#}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>